Add support for AMQP over RabbitMQ broker
DiamondLightSource/blueapi pull request #107
Opened 2023-03-31 13:24 UTC by DiamondJoseph

Closes #104 with support from command line and in helm

- [ ] Test CLi
- [ ] Test on Helm

2023-03-31 13:41 UTC, callumforrester requested changes
Looking good! Left a few comments, also to do:
* Linting needs fixing (`tox -e pre-commit,mypy` to run locally) 
* Tests are timing out
* Need rabbit as a service in CI

2023-03-31 13:41 UTC, callumforrester commented on src/blueapi/config.py
> +    impl: str = "stomp"
To make it a bit more spring-esque, I suggest making implementations independent of eachother. For example:
```suggestion
    using: List[str] = ["stomp"]
```

and then when instantiating:
```python
for impl in config.using:
    if impl == "stomp":
        ...
    elif impl == "amqp":
        ...
```

2023-03-31 13:41 UTC, callumforrester commented on src/blueapi/config.py
> +    password: str = "guest"  # Can only use guest/guest on loopback address
Do we need the capability to inject this via some sort of secret?

2023-03-31 13:41 UTC, callumforrester commented on src/blueapi/cli/cli.py
> +        client = StompMessagingTemplate.autoconfigured(StompConfig(host, port))
In the first case, `client` is a `MessagingClient` wrapping a `MessagingTemplate` instance. In the second case it is just a `MessagingTemplate` instance on its own. Is that right?

2023-05-03 09:06 UTC, DiamondJoseph commented
Superseded by #135

2023-05-03 09:06 UTC, closed without merging