Create documentation page about events
DiamondLightSource/blueapi pull request #152
Opened 2023-04-25 13:56 UTC by callumforrester

* Add page about events to developer documentation
* Explain why we need to add new events on top of the event model
* Explain the use of correlation IDs

2023-04-25 13:59 UTC, callumforrester commented
Still to do: make API reference and point to that

2023-05-04 10:51 UTC, DiamondJoseph requested changes
nit, otherwise LGTM

2023-05-04 10:51 UTC, DiamondJoseph commented on docs/developer/explanations/events.rst
> +sometimes assumes intuitive behavoir. The worker replaces the human and so must fill in the
behavoir -> behaviour

2023-05-04 10:52 UTC, DiamondJoseph commented
Presumably going to need an update for emitting state events on same topic?

2023-05-11 15:22 UTC, keithralphs commented
> Presumably going to need an update for emitting state events on same topic?

Do that as part of addressing #176

2023-05-11 15:29 UTC, merged