Standardise api
DiamondLightSource/blueapi pull request #222
Opened 2023-05-22 12:38 UTC by keithralphs

Rework the existing endpoints to comply with the guidelines:

- Making url object elements plural
- Changing PUT to POST for task creation
- Returning 201 for successful task creation
- Returning Location header of created resource on successful creation
- Adding version header to all endpoint responses

API version is set in app declaration after loading it from REST config object.
Added function to allow easy appending of endpoint specific response headers to defaults
Submit task method refactored to return task id (currently UUID)

2023-05-22 12:48 UTC, callumforrester requested changes
Thanks for doing this, just a couple of minor points. Also the CI is unhappy.

2023-05-22 14:08 UTC, keithralphs commented on src/blueapi/config.py
> +    version: str = "0.0.2"
Actually had that at first :)

2023-05-22 14:11 UTC, keithralphs commented on src/blueapi/service/main.py
> +    add_response_headers(response)
I'll take a look

2023-05-22 14:13 UTC, callumforrester commented on src/blueapi/service/main.py
> +async def get_plan_by_name(
It will be true of all of them

2023-05-22 14:31 UTC, keithralphs commented on src/blueapi/config.py
> +    version: str = "0.0.2"
Done

2023-05-22 14:32 UTC, keithralphs commented on src/blueapi/service/main.py
> +    add_response_headers(response)
Done

2023-05-22 14:32 UTC, keithralphs commented on src/blueapi/service/main.py
> +async def get_plan_by_name(
Done

2023-05-22 14:38 UTC, keithralphs commented
This PR is awaiting Callum's #202, which it will need to be rebased on top of. Until then the Liniting and tests will fail as the signature and purpose of the worker.submit_tasks method and its tests are in flux. Consequently do not merge this until #202 has been cleared and the rebase updates performed

2023-05-22 14:41 UTC, callumforrester commented on src/blueapi/service/main.py
> +def get_plans(response: Response, handler: Handler = Depends(get_handler)):
`response` is no longer used

2023-05-22 14:41 UTC, callumforrester commented on src/blueapi/service/main.py
> +    response: Response, name: str, handler: Handler = Depends(get_handler)
`response` is no longer used

2023-05-22 14:42 UTC, callumforrester commented on src/blueapi/service/main.py
> +def get_devices(response: Response, handler: Handler = Depends(get_handler)):
`response` is no longer used

2023-05-22 14:49 UTC, keithralphs commented on src/blueapi/service/main.py
> +def get_plans(response: Response, handler: Handler = Depends(get_handler)):
Done

2023-05-22 14:49 UTC, keithralphs commented on src/blueapi/service/main.py
> +    response: Response, name: str, handler: Handler = Depends(get_handler)
Done

2023-05-22 14:49 UTC, keithralphs commented on src/blueapi/service/main.py
> +def get_devices(response: Response, handler: Handler = Depends(get_handler)):
Done

2023-05-22 14:49 UTC, keithralphs commented on src/blueapi/service/main.py
> +    response: Response, name: str, handler: Handler = Depends(get_handler)
Done

2023-05-23 15:51 UTC, callumforrester approved these changes

2023-05-23 21:29 UTC, merged