Changes to ref p38 dodal
DiamondLightSource/blueapi pull request #281
Opened 2023-07-26 15:03 UTC by keithralphs

2023-08-15 10:33 UTC, DiamondJoseph requested changes

2023-08-15 10:33 UTC, DiamondJoseph commented on helm/blueapi/templates/deployment.yaml
> +          path: "/dls_sw/p38/software/bluesky_plans"
Un-hardcode this and get (this/these) from values.yaml if it exists

2023-08-15 10:33 UTC, DiamondJoseph commented on helm/blueapi/templates/deployment.yaml
> +              value: /plans
Calllum wants to only allow python modules and not just a random folder

2024-07-22 16:46 UTC, stan-dot commented
unclear ref changes, petition to close @callumforrester

2024-07-24 08:15 UTC, callumforrester commented
Yep, no longer needed

2024-07-24 08:15 UTC, closed without merging