Add page on adding plans and devices to blueapi
DiamondLightSource/blueapi pull request #291
Opened 2023-08-10 12:48 UTC by callumforrester

Document how to add plans and devices to blueapi.
This is an early draft meant to be criticised. The design it describes is also not the final design and can definitely be improved upon. Would be good to reduce the overall number of steps required to get a plan in!

2023-08-10 12:54 UTC, callumforrester commented
Preview of the page here: https://diamondlightsource.github.io/blueapi/plan-docs/index.html

2023-08-17 10:48 UTC, DominicOram requested changes
Thanks Callum, this is a good start. There's a lot of implied steps to this that are simple with some python knowledge but I don't think would be obvious to someone with a pure Java background like how to set up a python environment with all the constituent pieces for this to work. I realise this might not be the best place for a tutorial like that but I think we need one.

Ideally I think this guide (or maybe it's better suited to a tutorial) will walk you through the next steps on how to run `blueapi` pointing at this and how to then run a plan

2023-08-17 10:48 UTC, DominicOram commented on docs/user/how-to/add-plans-and-devices.rst
> +The easiest place to put the code is a repository created with the Python skeleton. Which can then become any of the above.
Could: Link to the python skeleton

2023-08-17 10:48 UTC, DominicOram commented on docs/user/how-to/add-plans-and-devices.rst
> +          module: dodal.my_beamline
Should: It's not immediately clear that this is referencing the file with `MyTypeOfDetector` in it

2023-08-17 10:50 UTC, DominicOram commented
> This is an early draft meant to be criticised. The design it describes is also not the final design and can definitely be improved upon. Would be good to reduce the overall number of steps required to get a plan in!

I don't think we should let this block us from merging it, we can change it later if we want.

2023-08-22 08:29 UTC, callumforrester commented
@DominicOram I've added a link to the skeleton and its "new project" documentation, which will hopefully help with the missing steps for Python novices part. Although I wouldn't be surprised if those tutorials have their own assumptions that we will discover.

2023-08-22 13:14 UTC, DominicOram approved these changes
Thanks, I think this a good start we should get merged

2023-08-22 13:17 UTC, merged