Improve Landing Page and Quickstart Guide
DiamondLightSource/blueapi pull request #292
Opened 2023-08-10 16:13 UTC by callumforrester

Addresses some of the concerns raised in #279 

Changes:
* Add concept explanation and diagram to documentation landing page
* Add brief description and testing instructions to quickstart guide

2023-08-10 16:21 UTC, callumforrester commented
Preview of landing page here: https://github.com/DiamondLightSource/blueapi/tree/welcome-page
Preview of docs changes here: https://diamondlightsource.github.io/blueapi/welcome-page/index.html

2023-08-17 10:58 UTC, DominicOram requested changes
Great, work, thanks. Not strictly part of this PR I guess but the CLI commands on `Quickstart`->`Start Worker` do not work for my latest install of `blueapi`

2023-08-17 10:58 UTC, DominicOram commented on README.rst
> +Wrap bluesky_ plans and devices inside a server and send commands/receive data.
Nit: The tense here is a bit odd
```suggestion
This module wraps bluesky_ plans and devices inside a server and exposes endpoints to send commands/receive data.
```

2023-08-17 11:02 UTC, callumforrester commented on README.rst
> +Wrap bluesky_ plans and devices inside a server and send commands/receive data.
Agree, that sounds much better

2023-08-17 11:06 UTC, callumforrester commented
@DominicOram The CLI commands work for me, could you confirm which version of blueapi you are using?
These commands should work for `>=0.3.0`

2023-08-17 13:51 UTC, DominicOram approved these changes
My bad, all good with latest `blueapi` version

2023-08-22 08:17 UTC, merged