migrate the docs
DiamondLightSource/blueapi pull request #448
Opened 2024-05-01 15:06 UTC by stan-dot

2024-05-01 15:24 UTC, stan-dot commented
> /home/runner/work/blueapi/blueapi/docs/reference.md:5: WARNING: toctree contains reference to document 'reference/cli' that doesn't have a title: no link will be generated
one small error with toctree extension - might be rst specific, need equivalent for md

2024-05-03 13:48 UTC, callumforrester requested changes
Git appears to see these as deleting old files and creating new ones, rather than renaming. Can we somehow preserve history?

2024-05-03 15:00 UTC, stan-dot commented
we cannot preserve that, renaming the file extension makes the change.

2024-05-03 15:06 UTC, DiamondJoseph commented
> we cannot preserve that, renaming the file extension makes the change.

Can you try renaming the files, committing, then replacing the contents, committing again?

2024-05-03 16:12 UTC, stan-dot commented
why do we care about the exact history? this app has only been run on 1 live beamline.

I'll check the history thing on Tuesday if time allows

2024-05-15 14:13 UTC, callumforrester commented
This needs to be two commits:
1. Changes the file names
2. Changes the file contents
It then needs to be merged _without_ squashing

2024-05-16 12:56 UTC, stan-dot commented
that here is quite odd

2024-05-16 14:20 UTC, stan-dot commented
todo: need to remove the sphinx dependency and the CI jobs: `ERROR: InvocationError for command /opt/hostedtoolcache/Python/3.11.9/x64/bin/sphinx-build -EW --keep-going -T docs build/html (exited with code 1)`

@callumforrester will the new markdown docs just livein the repo or do we build them and deploy to some place like github pages?

2024-05-17 14:11 UTC, callumforrester approved these changes

2024-05-20 08:44 UTC, DiamondJoseph commented on docs/reference/rest-spec.md
Don't these files require changes?

2024-05-20 08:44 UTC, DiamondJoseph commented on docs/reference/messaging-spec.md
Don't these files require changes?

2024-05-20 08:44 UTC, DiamondJoseph requested changes

2024-05-20 08:44 UTC, DiamondJoseph commented on docs/reference/cli.md
Don't these files require changes?

2024-05-20 09:18 UTC, stan-dot commented on docs/reference/rest-spec.md
ok will review those all

2024-05-20 09:18 UTC, stan-dot commented on docs/reference/messaging-spec.md
ok will review those all

2024-05-20 09:18 UTC, stan-dot commented on docs/reference/cli.md
ok will review those all

2024-05-20 10:02 UTC, stan-dot commented
what is this??? 
![image](https://github.com/DiamondLightSource/blueapi/assets/56644812/84b0483a-28d0-43bc-80cf-429ffb3e4e2d)

2024-05-20 10:02 UTC, stan-dot commented on docs/reference/messaging-spec.md
no idea what is this about, :show-nested:, it couldn't be less informative

2024-05-20 10:03 UTC, stan-dot commented on docs/reference/rest-spec.md
this done ok

2024-05-20 10:03 UTC, stan-dot commented on docs/reference/cli.md
no idea what is this about, :show-nested:, it couldn't be less informative

2024-05-20 10:03 UTC, stan-dot commented on docs/reference/messaging-spec.md
done

2024-05-20 10:14 UTC, DiamondJoseph commented
> what is this??? 

It appears to be embedding the rst inside the md rather than doing the equivalent md formatting :D

2024-05-20 10:16 UTC, stan-dot commented
> > what is this???
> 
> It appears to be embedding the rst inside the md rather than doing the equivalent md formatting :D

I know that , it's an artifact from a fully rst times. But what sorcery did it do behind the scenes to dynamically import version like that? Do we want to support this in md?

2024-05-20 10:25 UTC, DiamondJoseph commented
It's part of the configured tooling.
https://github.com/DiamondLightSource/blueapi/blob/main/pyproject.toml#L72

I think it is correct for it to be there (it is available to call `blueapi version` after pip installing)

2024-05-20 14:54 UTC, stan-dot commented
I don't think that markdown calls this rightly, this is redundant information that could be deleted from `api.md`

@DiamondJoseph

2024-05-20 14:55 UTC, stan-dot commented
f

2024-05-22 11:02 UTC, stan-dot commented
following [this comment](https://github.com/sphinx-doc/sphinx/issues/11739#issuecomment-1793687223)  to get it to work

2024-05-23 06:45 UTC, callumforrester approved these changes
LGTM, thanks!

2024-05-23 09:05 UTC, merged