Upgrade to Pydantic 2
DiamondLightSource/blueapi pull request #564
Opened 2024-07-19 08:43 UTC by callumforrester

Fixes #273 

Supersedes #449 

Currently scanspec is spoofed, we need https://github.com/bluesky/scanspec/issues/122 merged before we can revert.

2024-08-14 08:17 UTC, DiamondJoseph requested changes

2024-08-14 08:17 UTC, DiamondJoseph commented on pyproject.toml
> +    "scanspec>=0.7.0",
Since we know scanspec 0.7.0 isn't compatible with serialising BaseModels like we need to, let's keep it at >=0.7.1

2024-08-14 10:07 UTC, ZohebShaikh commented on src/blueapi/service/main.py
> -    on_shutdown=[teardown_runner],
https://fastapi.tiangolo.com/advanced/events/#shutdown-event

As we are using lifespan which declares both the startup and the shutdown ...
We cannot use both of them together

2024-08-14 10:07 UTC, ZohebShaikh commented on src/blueapi/cli/format.py
> +            elif any_of := spec.get("anyOf"):
It was Callum's work ..should I change something here ?

2024-08-14 10:25 UTC, DiamondJoseph commented on src/blueapi/cli/format.py
> +            elif any_of := spec.get("anyOf"):
Just wanted to know the motivation. @callumforrester are we still reflecting optional fields such that it's clear they're optional? I know the handling for nulls were changed in fastapi

2024-08-14 10:27 UTC, callumforrester commented on src/blueapi/cli/format.py
> +            elif any_of := spec.get("anyOf"):
The handling of null unions was changed in pydantic2, see [this comment](https://github.com/pydantic/pydantic/issues/7161#issuecomment-2275671152) (and the issue in general).

2024-08-14 10:29 UTC, callumforrester commented on src/blueapi/utils/base_model.py
> +    populate_by_name=True,
It was added to stop underscore fields being serialized. This appears to be the default behaviour in pydantic 2 now...

```python
>>> from pydantic import BaseModel
>>> class Foo(BaseModel):
...     bar: int
...     _baz: int
... 
>>> foo = Foo(bar=2, _baz=3)
>>> foo.model_dump()
{'bar': 2}

```

2024-08-14 12:11 UTC, DiamondJoseph commented on dev-requirements.txt
> +ophyd-async==0.3.1
also here. Would be nice to see those projects updated first

2024-08-20 12:31 UTC, DiamondJoseph approved these changes

2024-08-20 12:36 UTC, merged